// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _NumericValueFfi extends ffi.Struct {
  @ffi.Int32()
  external int value;
}

/// See the [Rust documentation for `NumericValue`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html) for more information.
final class NumericValue {
  // ignore: public_member_api_docs
  int value;

  // ignore: public_member_api_docs
  NumericValue({required this.value});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  NumericValue._fromFfi(_NumericValueFfi ffi) :
    value = ffi.value;

  // ignore: unused_element
  _NumericValueFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_NumericValueFfi>();
    struct.value = value;
    return struct;
  }

  /// See the [Rust documentation for `for_char`](https://docs.rs/icu/2.1.1/icu/properties/props/trait.EnumeratedProperty.html#tymethod.for_char) for more information.
  static NumericValue forChar(Rune ch) {
    final result = _icu4x_NumericValue_for_char_mv1(ch);
    return NumericValue._fromFfi(result);
  }

  /// See the [Rust documentation for `get`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html#method.get) for more information.
  double? get() {
    final temp = _FinalizedArena();
    final result = _icu4x_NumericValue_get_mv1(_toFfi(temp.arena));
    if (!result.isOk) {
      return null;
    }
    return result.union.ok;
  }

  /// Convert to an integer value usable with ICU4C and CodePointMapData
  ///
  /// See the [Rust documentation for `to_icu4c_value`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html#method.to_icu4c_value) for more information.
  int toIntegerValue() {
    final temp = _FinalizedArena();
    final result = _icu4x_NumericValue_to_integer_value_mv1(_toFfi(temp.arena));
    return result;
  }

  /// Convert from an integer value from ICU4C or CodePointMapData
  ///
  /// See the [Rust documentation for `from_icu4c_value`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html#method.from_icu4c_value) for more information.
  static NumericValue fromIntegerValue(int value) {
    final result = _icu4x_NumericValue_from_integer_value_mv1(value);
    return NumericValue._fromFfi(result);
  }


  @override
  bool operator ==(Object other) =>
      other is NumericValue &&
      other.value == value;

  @override
  int get hashCode => Object.hashAll([
        value,
      ]);
}

@_DiplomatFfiUse('icu4x_NumericValue_for_char_mv1')
@ffi.Native<_NumericValueFfi Function(ffi.Uint32)>(isLeaf: true, symbol: 'icu4x_NumericValue_for_char_mv1')
// ignore: non_constant_identifier_names
external _NumericValueFfi _icu4x_NumericValue_for_char_mv1(Rune ch);

@_DiplomatFfiUse('icu4x_NumericValue_get_mv1')
@ffi.Native<_ResultDoubleVoid Function(_NumericValueFfi)>(isLeaf: true, symbol: 'icu4x_NumericValue_get_mv1')
// ignore: non_constant_identifier_names
external _ResultDoubleVoid _icu4x_NumericValue_get_mv1(_NumericValueFfi self);

@_DiplomatFfiUse('icu4x_NumericValue_to_integer_value_mv1')
@ffi.Native<ffi.Int32 Function(_NumericValueFfi)>(isLeaf: true, symbol: 'icu4x_NumericValue_to_integer_value_mv1')
// ignore: non_constant_identifier_names
external int _icu4x_NumericValue_to_integer_value_mv1(_NumericValueFfi self);

@_DiplomatFfiUse('icu4x_NumericValue_from_integer_value_mv1')
@ffi.Native<_NumericValueFfi Function(ffi.Int32)>(isLeaf: true, symbol: 'icu4x_NumericValue_from_integer_value_mv1')
// ignore: non_constant_identifier_names
external _NumericValueFfi _icu4x_NumericValue_from_integer_value_mv1(int value);

// dart format on
