// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * See the [Rust documentation for `NumericValue`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html) for more information.
 */
export class NumericValue {
    #value;
    get value() {
        return this.#value;
    }
    set value(value){
        this.#value = value;
    }
    /** @internal */
    static fromFields(structObj) {
        return new NumericValue(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("NumericValue's constructor takes an object of NumericValue's fields.");
        }

        if ("value" in structObj) {
            this.#value = structObj.value;
        } else {
            throw new Error("Missing required field value.");
        }

        return this;
    }

    // Return this struct in FFI function friendly format.
    // Returns an array that can be expanded with spread syntax (...)
    _intoFFI(
        dst,
        functionCleanupArena,
        appendArrayMap
    ) {
        return this.#value;
    }

    static get _sizeBytes() {
        return 4;
    }

    /// Currently unused, we may want to use later on though:
    static get _sizeAlign() {
        return 4;
    }

    static _fromSuppliedValue(internalConstructor, obj) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("_fromSuppliedValue cannot be called externally.");
        }

        if (obj instanceof NumericValue) {
            return obj;
        }

        return NumericValue.fromFields(obj);
    }

    _writeToArrayBuffer(
        arrayBuffer,
        offset,
        functionCleanupArena,
        appendArrayMap
    ) {
        diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, this.#value, Int32Array);
    }

    // This struct contains borrowed fields, so this takes in a list of
    // "edges" corresponding to where each lifetime's data may have been borrowed from
    // and passes it down to individual fields containing the borrow.
    // This method does not attempt to handle any dependencies between lifetimes, the caller
    // should handle this when constructing edge arrays.
    static _fromFFI(internalConstructor, primitiveValue) {
        if (internalConstructor !== diplomatRuntime.internalConstructor) {
            throw new Error("NumericValue._fromFFI is not meant to be called externally. Please use the default constructor.");
        }
        let structObj = {};
        structObj.value = primitiveValue;

        return new NumericValue(structObj);
    }


    /**
     * See the [Rust documentation for `for_char`](https://docs.rs/icu/2.1.1/icu/properties/props/trait.EnumeratedProperty.html#tymethod.for_char) for more information.
     */
    static forChar(ch) {

        const result = wasm.icu4x_NumericValue_for_char_mv1(ch);

        try {
            return NumericValue._fromFFI(diplomatRuntime.internalConstructor, result);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * See the [Rust documentation for `get`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html#method.get) for more information.
     */
    get() {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 9, 8, true);


        const result = wasm.icu4x_NumericValue_get_mv1(diplomatReceive.buffer, NumericValue._fromSuppliedValue(diplomatRuntime.internalConstructor, this)._intoFFI(diplomatRuntime.FUNCTION_PARAM_ALLOC.alloc(NumericValue._sizeBytes), functionCleanupArena, {}, false));

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return (new Float64Array(wasm.memory.buffer, diplomatReceive.buffer, 1))[0];
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Convert to an integer value usable with ICU4C and CodePointMapData
     *
     * See the [Rust documentation for `to_icu4c_value`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html#method.to_icu4c_value) for more information.
     */
    toIntegerValue() {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();


        const result = wasm.icu4x_NumericValue_to_integer_value_mv1(NumericValue._fromSuppliedValue(diplomatRuntime.internalConstructor, this)._intoFFI(diplomatRuntime.FUNCTION_PARAM_ALLOC.alloc(NumericValue._sizeBytes), functionCleanupArena, {}, false));

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

        }
    }

    /**
     * Convert from an integer value from ICU4C or CodePointMapData
     *
     * See the [Rust documentation for `from_icu4c_value`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html#method.from_icu4c_value) for more information.
     */
    static fromIntegerValue(value) {

        const result = wasm.icu4x_NumericValue_from_integer_value_mv1(value);

        try {
            return NumericValue._fromFFI(diplomatRuntime.internalConstructor, result);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}