// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type NumericValue_obj = {
    value: number;
};



/**
 * See the [Rust documentation for `NumericValue`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html) for more information.
 */
export class NumericValue {
    get value(): number;
    set value(value: number);
    /** @internal */
    static fromFields(structObj : NumericValue_obj) : NumericValue;

    /**
    * Create `NumericValue` from an object that contains all of `NumericValue`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: NumericValue_obj);


    /**
     * See the [Rust documentation for `for_char`](https://docs.rs/icu/2.1.1/icu/properties/props/trait.EnumeratedProperty.html#tymethod.for_char) for more information.
     */
    static forChar(ch: codepoint): NumericValue;

    /**
     * See the [Rust documentation for `get`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html#method.get) for more information.
     */
    get(): number | null;

    /**
     * Convert to an integer value usable with ICU4C and CodePointMapData
     *
     * See the [Rust documentation for `to_icu4c_value`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html#method.to_icu4c_value) for more information.
     */
    toIntegerValue(): number;

    /**
     * Convert from an integer value from ICU4C or CodePointMapData
     *
     * See the [Rust documentation for `from_icu4c_value`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.NumericValue.html#method.from_icu4c_value) for more information.
     */
    static fromIntegerValue(value: number): NumericValue;
}